[package]
name = "novasmt"
version = "0.1.2"
authors = ["nullchinchilla <nullchinchilla@pm.me>"]
edition = "2018"
description="Storage-agnostic, highly ergonomic sparse Merkle trees"
license = "ISC"
repository="https://github.com/themeliolabs/novasmt"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
im="15"
serde={version="1", features=["derive"]}
bitvec="0.22"
blake3="0.3.7"
parking_lot="0.11"
dashmap="4"
bytes={version="1", features=["serde"]}
log="0.4"
scopeguard="1"
genawaiter="0.99.1"
hex="0.4"

[target.'cfg(fuzzing)'.dependencies]
honggfuzz="0.5"
env_logger="0.8"

[profile.release]
opt-level=3
debug=2
overflow-checks = true

[dev-dependencies]
criterion = "0.3"
env_logger="0.8"

[[bench]]
name = "criterion"
harness = false